# This is a config for E2B sandbox template.
# You can use template ID (cqywkz9c1ok0v8jcefj4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("cqywkz9c1ok0v8jcefj4") # Sync sandbox
# sandbox = await AsyncSandbox.create("cqywkz9c1ok0v8jcefj4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('cqywkz9c1ok0v8jcefj4')

team_id = "fa04bbd2-33ad-4e8e-badb-4caa88913ece"
start_cmd = "/compile_frontend.sh"
dockerfile = "e2b.Dockerfile"
template_id = "cqywkz9c1ok0v8jcefj4"
